name: Run API tests with Newman

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run API tests
        run: |
          newman run "api-tests/lesson-14/BobMarly - lesson 14 CI-CD Postman CLI.postman_collection.json" \
            -e "api-tests/lesson-14/Todois.postman_environment.json" \
            -r cli,html \
            --reporter-html-export newman-report.html

      - name: Upload report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: newman-report
          path: newman-report.html
